export const metricData = [
  { "metricType": 1, "metricCode": "ACTIVE_SECONDS", "metricName": "Active Time" },
  { "metricType": 2, "metricCode": "REST_SECONDS", "metricName": "Rest Time" },
  { "metricType": 3, "metricCode": "LOW_INTENSITY_SECONDS", "metricName": "Low Activity Time" },
  { "metricType": 4, "metricCode": "MODERATE_INTENSITY_SECONDS", "metricName": "Moderate Activity Time" },
  { "metricType": 5, "metricCode": "VIGOROUS_INTENSITY_SECONDS", "metricName": "Hard Workout Time" },
  { "metricType": 6, "metricCode": "CALORIES_EXPENDITURE", "metricName": "Calories Burned" },
  { "metricType": 7, "metricCode": "CALORIES_NET_ACTIVE", "metricName": "Active Calories" },
  { "metricType": 8, "metricCode": "CALORIES_BMR", "metricName": "BMR Calories" },
  { "metricType": 9, "metricCode": "STEPS", "metricName": "Steps" },
  { "metricType": 10, "metricCode": "WALKED_DISTANCE", "metricName": "Walking Distance" },
  { "metricType": 11, "metricCode": "TRAVELED_DISTANCE", "metricName": "Distance Traveled" },
  { "metricType": 12, "metricCode": "FLOORS_CLIMBED", "metricName": "Floors Climbed" },
  { "metricType": 13, "metricCode": "SWIMMING_NUM_STROKES", "metricName": "Swim Strokes" },
  { "metricType": 14, "metricCode": "SWIMMING_NUM_LAPS", "metricName": "Swim Laps" },
  { "metricType": 15, "metricCode": "ACTIVE_STEPS", "metricName": "Active Steps" },
  { "metricType": 16, "metricCode": "HR_MAX", "metricName": "Max Heart Rate" },
  { "metricType": 17, "metricCode": "HR_MIN", "metricName": "Min Heart Rate" },
  { "metricType": 18, "metricCode": "HR_AVG", "metricName": "Heart Rate Avg" },
  { "metricType": 19, "metricCode": "HR_RESTING", "metricName": "Resting Heart Rate" },
  { "metricType": 20, "metricCode": "HRV_RMSSD", "metricName": "HRV" },
  { "metricType": 21, "metricCode": "HRV_SDNN", "metricName": "HRV SDNN" },
  { "metricType": 22, "metricCode": "OXYGENATION_SATURATION", "metricName": "Blood Oxygen" },
  { "metricType": 23, "metricCode": "VO2MAX", "metricName": "Fitness Level" },
  { "metricType": 24, "metricCode": "STRESS_AVG", "metricName": "Stress Avg" },
  { "metricType": 25, "metricCode": "STRESS_MAX", "metricName": "Stress Max" },
  { "metricType": 26, "metricCode": "BLOOD_GLUCOSE", "metricName": "Blood Glucose" },
  { "metricType": 27, "metricCode": "BLOOD_PRESSURE_SYSTOLIC", "metricName": "BP Systolic" },
  { "metricType": 28, "metricCode": "BLOOD_PRESSURE_DIASTOLIC", "metricName": "BP Diastolic" },
  { "metricType": 29, "metricCode": "WAIST_CIRCUMFERENCE", "metricName": "Waist Size" },
  { "metricType": 30, "metricCode": "HIP_CIRCUMFERENCE", "metricName": "Hip Size" },
  { "metricType": 31, "metricCode": "CHEST_CIRCUMFERENCE", "metricName": "Chest Size" },
  { "metricType": 32, "metricCode": "BONE_COMPOSITION", "metricName": "Bone %" },
  { "metricType": 33, "metricCode": "MUSCLE_COMPOSITION", "metricName": "Muscle %" },
  { "metricType": 34, "metricCode": "WATER_COMPOSITION", "metricName": "Body Water %" },
  { "metricType": 35, "metricCode": "WEIGHT", "metricName": "Weight" },
  { "metricType": 36, "metricCode": "HEIGHT", "metricName": "Height" },
  { "metricType": 37, "metricCode": "BMI", "metricName": "BMI" },
  { "metricType": 38, "metricCode": "WATER_TOTAL_CONSUMPTION", "metricName": "Water Intake" },
  { "metricType": 39, "metricCode": "CALORIES_INTAKE", "metricName": "Calories Intake" },
  { "metricType": 40, "metricCode": "PROTEIN_INTAKE", "metricName": "Protein Intake" },
  { "metricType": 41, "metricCode": "SUGAR_INTAKE", "metricName": "Sugar Intake" },
  { "metricType": 42, "metricCode": "FAT_INTAKE", "metricName": "Fat Intake" },
  { "metricType": 43, "metricCode": "CARBS_INTAKE", "metricName": "Carbs Intake" },
  { "metricType": 44, "metricCode": "FIBER_INTAKE", "metricName": "Fiber Intake" },
  { "metricType": 45, "metricCode": "SODIUM_INTAKE", "metricName": "Sodium Intake" },
  { "metricType": 46, "metricCode": "CHOLESTEROL_INTAKE", "metricName": "Cholesterol Intake" },
  { "metricType": 47, "metricCode": "SLEEP_DURATION", "metricName": "Sleep Duration" },
  { "metricType": 48, "metricCode": "TIME_IN_BED", "metricName": "Time in Bed" },
  { "metricType": 49, "metricCode": "LIGHT_SLEEP_DURATION", "metricName": "Light Sleep" },
  { "metricType": 50, "metricCode": "REM_SLEEP_DURATION", "metricName": "REM Sleep" },
  { "metricType": 51, "metricCode": "DEEP_SLEEP_DURATION", "metricName": "Deep Sleep" },
  { "metricType": 52, "metricCode": "TIME_TO_FALL_ASLEEP", "metricName": "Sleep Onset Time" },
  { "metricType": 53, "metricCode": "TIME_AWAKE", "metricName": "Awake Time" },
  { "metricType": 54, "metricCode": "SLEEP_QUALITY_SCORE", "metricName": "Sleep Score" },
  { "metricType": 55, "metricCode": "SLEEP_EFFICIENCY", "metricName": "Sleep Efficiency" },
  { "metricType": 56, "metricCode": "STEPS_ACCUMULATED", "metricName": "Total Steps" },
  { "metricType": 60, "metricCode": "HR_EVENT_RESTING", "metricName": "Resting HR (Event)" },
  { "metricType": 61, "metricCode": "HRV_EVENT_RMSSD", "metricName": "Event HRV" },
  { "metricType": 62, "metricCode": "HRV_EVENT_SDNN", "metricName": "Event HRV SDNN" },
  { "metricType": 63, "metricCode": "BP_EVENT_SYSTOLIC", "metricName": "BP Systolic (Event)" },
  { "metricType": 64, "metricCode": "BP_EVENT_DIASTOLIC", "metricName": "BP Diastolic (Event)" },
  { "metricType": 65, "metricCode": "STRESS_DURATION", "metricName": "Stress Time" },
  { "metricType": 66, "metricCode": "SNORING_DURATION", "metricName": "Snoring Time" },
  { "metricType": 67, "metricCode": "SNORING_EVENTS", "metricName": "Snoring Events" },
  { "metricType": 68, "metricCode": "BODY_FAT", "metricName": "Body Fat" },
  { "metricType": 69, "metricCode": "MUSCLE_MASS", "metricName": "Muscle Mass" },
  { "metricType": 70, "metricCode": "BONE_MASS", "metricName": "Bone Mass" },
  { "metricType": 71, "metricCode": "WATER_PERCENTAGE", "metricName": "Water %" },
  { "metricType": 72, "metricCode": "ACTIVITY_OTHER", "metricName": "Other Activity" },
  { "metricType": 73, "metricCode": "ACTIVITY_RUNNING", "metricName": "Running" },
  { "metricType": 74, "metricCode": "ACTIVITY_WALKING", "metricName": "Walking" },
  { "metricType": 75, "metricCode": "ACTIVITY_CYCLING", "metricName": "Cycling" },
  { "metricType": 76, "metricCode": "ACTIVITY_SWIMMING", "metricName": "Swimming" },
  { "metricType": 77, "metricCode": "ACTIVITY_HIKING", "metricName": "Hiking" },
  { "metricType": 78, "metricCode": "ACTIVITY_YOGA", "metricName": "Yoga" },
  { "metricType": 79, "metricCode": "ACTIVITY_STRENGTH_TRAINING", "metricName": "Strength Training" },
  { "metricType": 80, "metricCode": "ACTIVITY_CARDIO", "metricName": "Cardio" }
]
