export const metricData = [
  {
    metricType: 1,
    metricCode: "ACTIVE_SECONDS",
    metricName: "Active Time",
    metricIcon: "https://api.iconify.design/mdi/run.svg",
  },
  {
    metricType: 2,
    metricCode: "REST_SECONDS",
    metricName: "Rest Time",
    metricIcon: "https://api.iconify.design/mdi/sleep.svg",
  },
  {
    metricType: 3,
    metricCode: "LOW_INTENSITY_SECONDS",
    metricName: "Low Activity Time",
    metricIcon: "https://api.iconify.design/mdi/walk.svg",
  },
  {
    metricType: 4,
    metricCode: "MODERATE_INTENSITY_SECONDS",
    metricName: "Moderate Activity Time",
    metricIcon: "https://api.iconify.design/mdi/run-fast.svg",
  },
  {
    metricType: 5,
    metricCode: "VIGOROUS_INTENSITY_SECONDS",
    metricName: "Hard Workout Time",
    metricIcon: "https://api.iconify.design/mdi/dumbbell.svg",
  },
  {
    metricType: 6,
    metricCode: "CALORIES_EXPENDITURE",
    metricName: "Calories Burned",
    metricIcon: "https://api.iconify.design/mdi/fire.svg",
  },
  {
    metricType: 7,
    metricCode: "CALORIES_NET_ACTIVE",
    metricName: "Active Calories",
    metricIcon: "https://api.iconify.design/mdi/fire-circle.svg",
  },
  {
    metricType: 8,
    metricCode: "CALORIES_BMR",
    metricName: "BMR Calories",
    metricIcon: "https://api.iconify.design/mdi/food-apple.svg",
  },
  {
    metricType: 9,
    metricCode: "STEPS",
    metricName: "Steps",
    metricIcon: "https://api.iconify.design/mdi/foot-print.svg",
  },
  {
    metricType: 10,
    metricCode: "WALKED_DISTANCE",
    metricName: "Walking Distance",
    metricIcon: "https://api.iconify.design/mdi/map-marker-distance.svg",
  },
  {
    metricType: 11,
    metricCode: "TRAVELED_DISTANCE",
    metricName: "Distance Traveled",
    metricIcon: "https://api.iconify.design/mdi/road-variant.svg",
  },
  {
    metricType: 12,
    metricCode: "FLOORS_CLIMBED",
    metricName: "Floors Climbed",
    metricIcon: "https://api.iconify.design/mdi/stairs-up.svg",
  },
  {
    metricType: 13,
    metricCode: "SWIMMING_NUM_STROKES",
    metricName: "Swim Strokes",
    metricIcon: "https://api.iconify.design/mdi/swim.svg",
  },
  {
    metricType: 14,
    metricCode: "SWIMMING_NUM_LAPS",
    metricName: "Swim Laps",
    metricIcon: "https://api/iconify.design/mdi/pool.svg",
  },
  {
    metricType: 15,
    metricCode: "ACTIVE_STEPS",
    metricName: "Active Steps",
    metricIcon: "https://api.iconify.design/mdi/shoe-print.svg",
  },

  {
    metricType: 16,
    metricCode: "HR_MAX",
    metricName: "Max Heart Rate",
    metricIcon: "https://api.iconify.design/mdi/heart-pulse.svg",
  },
  {
    metricType: 17,
    metricCode: "HR_MIN",
    metricName: "Min Heart Rate",
    metricIcon: "https://api.iconify.design/mdi/heart-clock.svg",
  },
  {
    metricType: 18,
    metricCode: "HR_AVG",
    metricName: "Heart Rate Avg",
    metricIcon: "https://api.iconify.design/mdi/heart.svg",
  },
  {
    metricType: 19,
    metricCode: "HR_RESTING",
    metricName: "Resting Heart Rate",
    metricIcon: "https://api.iconify.design/mdi/heart-off.svg",
  },

  {
    metricType: 20,
    metricCode: "HRV_RMSSD",
    metricName: "HRV",
    metricIcon: "https://api.iconify.design/mdi/heart-multiple.svg",
  },
  {
    metricType: 21,
    metricCode: "HRV_SDNN",
    metricName: "HRV SDNN",
    metricIcon: "https://api.iconify.design/mdi/heart-half-full.svg",
  },

  {
    metricType: 22,
    metricCode: "OXYGENATION_SATURATION",
    metricName: "Blood Oxygen",
    metricIcon: "https://api.iconify.design/mdi/oxygen-tank.svg",
  },
  {
    metricType: 23,
    metricCode: "VO2MAX",
    metricName: "Fitness Level",
    metricIcon: "https://api.iconify.design/mdi/arm-flex.svg",
  },

  {
    metricType: 24,
    metricCode: "STRESS_AVG",
    metricName: "Stress Avg",
    metricIcon: "https://api.iconify.design/mdi/emoticon-neutral.svg",
  },
  {
    metricType: 25,
    metricCode: "STRESS_MAX",
    metricName: "Stress Max",
    metricIcon: "https://api.iconify.design/mdi/emoticon-angry.svg",
  },

  {
    metricType: 26,
    metricCode: "BLOOD_GLUCOSE",
    metricName: "Blood Glucose",
    metricIcon: "https://api.iconify.design/mdi/needle.svg",
  },
  {
    metricType: 27,
    metricCode: "BLOOD_PRESSURE_SYSTOLIC",
    metricName: "BP Systolic",
    metricIcon: "https://api.iconify.design/mdi/heart-pulse.svg",
  },
  {
    metricType: 28,
    metricCode: "BLOOD_PRESSURE_DIASTOLIC",
    metricName: "BP Diastolic",
    metricIcon: "https://api.iconify.design/mdi/heart-pulse.svg",
  },

  {
    metricType: 29,
    metricCode: "WAIST_CIRCUMFERENCE",
    metricName: "Waist Size",
    metricIcon: "https://api.iconify.design/mdi/tape-measure.svg",
  },
  {
    metricType: 30,
    metricCode: "HIP_CIRCUMFERENCE",
    metricName: "Hip Size",
    metricIcon: "https://api.iconify.design/mdi/tape-measure.svg",
  },
  {
    metricType: 31,
    metricCode: "CHEST_CIRCUMFERENCE",
    metricName: "Chest Size",
    metricIcon: "https://api.iconify.design/mdi/tape-measure.svg",
  },

  {
    metricType: 32,
    metricCode: "BONE_COMPOSITION",
    metricName: "Bone %",
    metricIcon: "https://api.iconify.design/mdi/bone.svg",
  },
  {
    metricType: 33,
    metricCode: "MUSCLE_COMPOSITION",
    metricName: "Muscle %",
    metricIcon: "https://api.iconify.design/mdi/arm-flex.svg",
  },
  {
    metricType: 34,
    metricCode: "WATER_COMPOSITION",
    metricName: "Body Water %",
    metricIcon: "https://api.iconify.design/mdi/water-percent.svg",
  },

  {
    metricType: 35,
    metricCode: "WEIGHT",
    metricName: "Weight",
    metricIcon: "https://api.iconify.design/mdi/scale-bathroom.svg",
  },
  {
    metricType: 36,
    metricCode: "HEIGHT",
    metricName: "Height",
    metricIcon: "https://api.iconify.design/mdi/human-male-height.svg",
  },
  {
    metricType: 37,
    metricCode: "BMI",
    metricName: "BMI",
    metricIcon: "https://api.iconify.design/mdi/human-male-height-variant.svg",
  },

  {
    metricType: 38,
    metricCode: "WATER_TOTAL_CONSUMPTION",
    metricName: "Water Intake",
    metricIcon: "https://api.iconify.design/mdi/water.svg",
  },
  {
    metricType: 39,
    metricCode: "CALORIES_INTAKE",
    metricName: "Calories Intake",
    metricIcon: "https://api.iconify.design/mdi/food.svg",
  },
  {
    metricType: 40,
    metricCode: "PROTEIN_INTAKE",
    metricName: "Protein Intake",
    metricIcon: "https://api.iconify.design/mdi/food-turkey.svg",
  },
  {
    metricType: 41,
    metricCode: "SUGAR_INTAKE",
    metricName: "Sugar Intake",
    metricIcon: "https://api.iconify.design/mdi/cube-outline.svg",
  },
  {
    metricType: 42,
    metricCode: "FAT_INTAKE",
    metricName: "Fat Intake",
    metricIcon: "https://api.iconify.design/mdi/sausage.svg",
  },
  {
    metricType: 43,
    metricCode: "CARBS_INTAKE",
    metricName: "Carbs Intake",
    metricIcon: "https://api.iconify.design/mdi/noodles.svg",
  },
  {
    metricType: 44,
    metricCode: "FIBER_INTAKE",
    metricName: "Fiber Intake",
    metricIcon: "https://api.iconify.design/mdi/wheat.svg",
  },
  {
    metricType: 45,
    metricCode: "SODIUM_INTAKE",
    metricName: "Sodium Intake",
    metricIcon: "https://api.iconify.design/mdi/salt.svg",
  },
  {
    metricType: 46,
    metricCode: "CHOLESTEROL_INTAKE",
    metricName: "Cholesterol Intake",
    metricIcon: "https://api.iconify.design/mdi/food-variant.svg",
  },

  {
    metricType: 47,
    metricCode: "SLEEP_DURATION",
    metricName: "Sleep Duration",
    metricIcon: "https://api.iconify.design/mdi/sleep.svg",
  },
  {
    metricType: 48,
    metricCode: "TIME_IN_BED",
    metricName: "Time in Bed",
    metricIcon: "https://api.iconify.design/mdi/bed.svg",
  },
  {
    metricType: 49,
    metricCode: "LIGHT_SLEEP_DURATION",
    metricName: "Light Sleep",
    metricIcon:
      "https://api.iconify.design/mdi/weather-night-partly-cloudy.svg",
  },
  {
    metricType: 50,
    metricCode: "REM_SLEEP_DURATION",
    metricName: "REM Sleep",
    metricIcon: "https://api.iconify.design/mdi/weather-night.svg",
  },
  {
    metricType: 51,
    metricCode: "DEEP_SLEEP_DURATION",
    metricName: "Deep Sleep",
    metricIcon: "https://api.iconify.design/mdi/sleep.svg",
  },
  {
    metricType: 52,
    metricCode: "TIME_TO_FALL_ASLEEP",
    metricName: "Sleep Onset Time",
    metricIcon: "https://api.iconify.design/mdi/timer-sand.svg",
  },
  {
    metricType: 53,
    metricCode: "TIME_AWAKE",
    metricName: "Awake Time",
    metricIcon: "https://api.iconify.design/mdi/alarm.svg",
  },
  {
    metricType: 54,
    metricCode: "SLEEP_QUALITY_SCORE",
    metricName: "Sleep Score",
    metricIcon: "https://api.iconify.design/mdi/star-half-full.svg",
  },
  {
    metricType: 55,
    metricCode: "SLEEP_EFFICIENCY",
    metricName: "Sleep Efficiency",
    metricIcon: "https://api.iconify.design/mdi/chart-line.svg",
  },
  {
    metricType: 56,
    metricCode: "STEPS_ACCUMULATED",
    metricName: "Total Steps",
    metricIcon: "https://api.iconify.design/mdi/shoe-print.svg",
  },

  {
    metricType: 60,
    metricCode: "HR_EVENT_RESTING",
    metricName: "Resting HR (Event)",
    metricIcon: "https://api.iconify.design/mdi/heart.svg",
  },
  {
    metricType: 61,
    metricCode: "HRV_EVENT_RMSSD",
    metricName: "Event HRV",
    metricIcon: "https://api.iconify.design/mdi/heart-multiple-outline.svg",
  },
  {
    metricType: 62,
    metricCode: "HRV_EVENT_SDNN",
    metricName: "Event HRV SDNN",
    metricIcon: "https://api.iconify.design/mdi/heart-half.svg",
  },

  {
    metricType: 63,
    metricCode: "BP_EVENT_SYSTOLIC",
    metricName: "BP Systolic (Event)",
    metricIcon: "https://api.iconify.design/mdi/heart-pulse.svg",
  },
  {
    metricType: 64,
    metricCode: "BP_EVENT_DIASTOLIC",
    metricName: "BP Diastolic (Event)",
    metricIcon: "https://api.iconify.design/mdi/heart-pulse.svg",
  },

  {
    metricType: 65,
    metricCode: "STRESS_DURATION",
    metricName: "Stress Time",
    metricIcon: "https://api.iconify.design/mdi/emoticon-sad.svg",
  },
  {
    metricType: 66,
    metricCode: "SNORING_DURATION",
    metricName: "Snoring Time",
    metricIcon: "https://api.iconify.design/mdi/weather-windy.svg",
  },
  {
    metricType: 67,
    metricCode: "SNORING_EVENTS",
    metricName: "Snoring Events",
    metricIcon: "https://api.iconify.design/mdi/weather-windy-variant.svg",
  },

  {
    metricType: 68,
    metricCode: "BODY_FAT",
    metricName: "Body Fat",
    metricIcon: "https://api.iconify.design/mdi/scale.svg",
  },
  {
    metricType: 69,
    metricCode: "MUSCLE_MASS",
    metricName: "Muscle Mass",
    metricIcon: "https://api.iconify.design/mdi/arm-flex.svg",
  },
  {
    metricType: 70,
    metricCode: "BONE_MASS",
    metricName: "Bone Mass",
    metricIcon: "https://api.iconify.design/mdi/bone.svg",
  },
  {
    metricType: 71,
    metricCode: "WATER_PERCENTAGE",
    metricName: "Water %",
    metricIcon: "https://api.iconify.design/mdi/water-percent.svg",
  },

  {
    metricType: 72,
    metricCode: "ACTIVITY_OTHER",
    metricName: "Other Activity",
    metricIcon: "https://api.iconify.design/mdi/run.svg",
  },
  {
    metricType: 73,
    metricCode: "ACTIVITY_RUNNING",
    metricName: "Running",
    metricIcon: "https://api.iconify.design/mdi/run.svg",
  },
  {
    metricType: 74,
    metricCode: "ACTIVITY_WALKING",
    metricName: "Walking",
    metricIcon: "https://api.iconify.design/mdi/walk.svg",
  },
  {
    metricType: 75,
    metricCode: "ACTIVITY_CYCLING",
    metricName: "Cycling",
    metricIcon: "https://api.iconify.design/mdi/bicycle.svg",
  },
  {
    metricType: 76,
    metricCode: "ACTIVITY_SWIMMING",
    metricName: "Swimming",
    metricIcon: "https://api.iconify.design/mdi/swim.svg",
  },
  {
    metricType: 77,
    metricCode: "ACTIVITY_HIKING",
    metricName: "Hiking",
    metricIcon: "https://api.iconify.design/mdi/hiking.svg",
  },
  {
    metricType: 78,
    metricCode: "ACTIVITY_YOGA",
    metricName: "Yoga",
    metricIcon: "https://api.iconify.design/mdi/yoga.svg",
  },
  {
    metricType: 79,
    metricCode: "ACTIVITY_STRENGTH_TRAINING",
    metricName: "Strength Training",
    metricIcon: "https://api.iconify.design/mdi/dumbbell.svg",
  },
  {
    metricType: 80,
    metricCode: "ACTIVITY_CARDIO",
    metricName: "Cardio",
    metricIcon: "https://api.iconify.design/mdi/heart-pulse.svg",
  },
];
